---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-shmila-iaf-v1-go
  failurePolicy: Fail
  name: vgo.kb.io
  rules:
  - apiGroups:
    - shmila.iaf
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - goes
  sideEffects: None
