# permissions for end users to view goes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: go-viewer-role
rules:
- apiGroups:
  - shmila.iaf
  resources:
  - goes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - shmila.iaf
  resources:
  - goes/status
  verbs:
  - get
