apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
  name: go-operator-manager-role
  namespace: go-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - delete
  - update
  - list
