apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-server
  name: shmila
  namespace: shmila
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-server
  sessionAffinity: None
  type: ClusterIP