apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: go-operator-manager-rolebinding
  namespace: shmila
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: go-operator-manager-role
subjects:
- kind: ServiceAccount
  name: shmila-sa
  namespace: shmila
