apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: go-operator-manager-role
  namespace: shmila
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - patch
  - delete
  - create