apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: shmila/go-operator-serving-cert
  name: go-operator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: go-operator-webhook-service
      namespace: shmila
      path: /validate-shmila-iaf-v1-go
  failurePolicy: Fail
  name: vgo.kb.io
  rules:
  - apiGroups:
    - shmila.iaf
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - goes
  sideEffects: None
