apiVersion: v1
kind: Service
metadata:
  name: go-operator-webhook-service
  namespace: shmila
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
